sudo: false
language: node_js
node_js:
- '6'
- '7'
cache:
  bundler: true
  directories:
  - node_modules

install:
- npm i npminstall && npminstall

script:
- npm run test
- npm run ci

after_script:
- npminstall codecov && codecov
